language: c
sudo: required
install:
        wget https://raw.githubusercontent.com/anmaped/rmtld3synth/dev/.travis-opam.sh

script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.03
os:
  - linux
  - osx
