language: generic
dist: xenial

script:
  - wget https://raw.githubusercontent.com/anmaped/rmtld3synth/master/.travis-opam.sh
  - BASE_REMOTE=git+https://github.com/ocaml/opam-repository.git bash -ex .travis-opam.sh

addons:
  apt:
    packages:
    - git
    - build-essential
    - wget
    - software-properties-common
    - unzip
    - m4
    - python2.7
    - libgmp-dev
    - clang-format

env:
  - OCAML_VERSION=4.04 PACKAGE=rmtld3synth
  - OCAML_VERSION=4.14 PACKAGE=rmtld3synth

os:
  - linux
  - osx

jobs:
  exclude:
  - env: OCAML_VERSION=4.04 PACKAGE=rmtld3synth
    os: osx
