name: Run Unit Tests

on:
  workflow_run:
    workflows:
      - Publish Docker image
    branches:
      - v0.5-x
      - v0.5
    types:
      - completed

jobs:
  run_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: run anmaped/rmtld3synth image
        run: |
          docker run --rm \
          --entrypoint /bin/bash \
          -v ${PWD}:/workspace/source:z  \
          docker.io/anmaped/rmtld3synth:v0.5-x \
          -c 'cp -r /workspace/source /localsource && cd /localsource && \
          eval $(opam env) && \
          ./configure && make && make tests'